/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the current user and active organization.
         * @description Returns the authenticated user's profile and active organization. Just-in-time provisions the local user on first call (FR-013). A brand-new user has an empty membership set and a null activeOrganizationId (empty state, FR-005 edge case).
         */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/active-organization": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Set the active organization.
         * @description Sets the caller's active organization (FR-006). The target MUST be an organization the caller is a member of; otherwise a 404 is returned that is indistinguishable from a nonexistent organization (FR-007, FR-009, hide-existence). The previous selection is left unchanged on failure.
         */
        put: operations["setActiveOrganization"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List organizations the caller belongs to.
         * @description Returns exactly the organizations the caller is a member of and no others (FR-005, SC-003). This is the sanctioned cross-organization read (Principle V carve-out). Offset-paginated envelope (Principle III).
         */
        get: operations["listMyOrganizations"];
        put?: never;
        /**
         * Create a new organization.
         * @description Creates an organization and records the caller as its Owner (FR-001/002). A newly created organization contains only its Owner (FR-003). If the caller had no active organization, the new one becomes active (FR-014).
         */
        post: operations["createOrganization"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations/{organizationId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get an organization the caller belongs to.
         * @description Returns the organization only if the caller is a member. For a non-member — or a nonexistent organization — returns an identical 404 (FR-008/009, SC-002, hide-existence). No response reveals whether the organization exists.
         */
        get: operations["getOrganization"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Organization role. Only Owner exists in this slice.
         * @enum {string}
         */
        OrgRole: "Owner";
        MeResponse: {
            /** Format: uuid */
            userId: string;
            displayName?: string | null;
            /**
             * Format: uuid
             * @description Null when the user belongs to no organization (empty state).
             */
            activeOrganizationId: string | null;
        };
        CreateOrganizationRequest: {
            /** @description Non-empty, non-whitespace, ≤100 chars (FR-012). */
            name: string;
        };
        SetActiveOrganizationRequest: {
            /** Format: uuid */
            organizationId: string;
        };
        OrganizationSummary: {
            /** Format: uuid */
            id: string;
            name: string;
            role: components["schemas"]["OrgRole"];
        };
        OrganizationDetail: components["schemas"]["OrganizationSummary"] & {
            memberCount: number;
            /** Format: date-time */
            createdAt: string;
        };
        /** @description The one pagination envelope used by all list endpoints (Principle III). */
        PagedOrganizationSummary: {
            items: components["schemas"]["OrganizationSummary"][];
            page: number;
            pageSize: number;
            totalCount: number;
        };
        /** @description RFC 9457 problem details. */
        ProblemDetails: {
            /** Format: uri */
            type?: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
        };
    };
    responses: {
        /** @description Missing or invalid access token. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description The organization does not exist OR the caller is not a member — these are deliberately indistinguishable (hide-existence). */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
        /** @description The request failed validation. */
        ValidationProblem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
    };
    parameters: {
        Page: number;
        PageSize: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    setActiveOrganization: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetActiveOrganizationRequest"];
            };
        };
        responses: {
            /** @description Active organization updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            400: components["responses"]["ValidationProblem"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listMyOrganizations: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                pageSize?: components["parameters"]["PageSize"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The caller's organizations (possibly empty). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedOrganizationSummary"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createOrganization: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrganizationRequest"];
            };
        };
        responses: {
            /** @description Organization created. */
            201: {
                headers: {
                    /** @description URL of the created organization. */
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationSummary"];
                };
            };
            400: components["responses"]["ValidationProblem"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getOrganization: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Organization detail (caller is a member). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationDetail"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
}
