// Static Web App (Free) that hosts the React SPA — feature 002, US1 / FR-027.
//
// WHY THIS LIVES IN infra-web/ AND NOT infra/
// -------------------------------------------
// `infra/` is GENERATED by `azd infra gen` from the Aspire AppHost, and the CI
// infra-drift job diffs it against a fresh regeneration. A hand-written template
// placed there would be erased on the next regeneration and fail that job.
//
// WHY THIS IS NOT AN azd SERVICE
// ------------------------------
// azd forbids pairing an Aspire service with a sibling service, which is the
// documented reason the React app was excluded from azure.yaml's `services` in
// the first place. Adding it back would break `azd up` for the API too.
//
// So it deploys by the third route: a DECLARED HOOK in azure.yaml, the same path
// infra/budget.bicep already uses. Under constitution v1.1.0 that is a
// first-class deploy path, and scripts/check-idle-cost.* recognises it — a
// template reachable only this way is legitimate, not dead infrastructure.
//
// COST: the Free SKU has no standing charge, which is what the constitution's
// Deployment & Cost Constraints require for the React app ("hosted on Azure
// Static Web Apps (Free)"). Do not raise this to Standard: linked backends and
// custom auth would become available, but so would a monthly bill, and the
// same-origin proxy they enable is explicitly not the design here (research R10).

@description('Location for the Static Web App. Static Web Apps is available in a limited set of regions, which need not match the API region.')
param location string = 'eastus2'

@description('Name of the Static Web App resource.')
param name string = 'swa-sprint-sync'

@description('Tags applied to the resource, so azd-provisioned and hook-provisioned resources are identifiable together.')
param tags object = {}

resource web 'Microsoft.Web/staticSites@2024-04-01' = {
  name: name
  location: location
  tags: tags
  sku: {
    // Free tier. See the cost note above before changing this.
    name: 'Free'
    tier: 'Free'
  }
  properties: {
    // Content is published by the deploy workflow using the deployment token,
    // not by a repository integration: the workflow needs build-time environment
    // values (identity settings and the deployed API URL) that a provider-managed
    // build cannot supply. See .github/workflows/deploy-web.yml and research R12.
    provider: 'Custom'
    // No staging environments on Free, and none wanted: one environment is the
    // documented scope of this feature.
    stagingEnvironmentPolicy: 'Disabled'
    allowConfigFileUpdates: true
  }
}

@description('The hosted origin. Required by the API CORS policy (FR-030) and by the identity redirect URI (FR-031) — neither can be configured until this exists.')
output defaultHostname string = 'https://${web.properties.defaultHostname}'

@description('Resource name, for the workflow that fetches the deployment token.')
output name string = web.name
